-- Database for daily tasks (French)
-- coding: utf-8 'ä

SimplifiedTasksDatas = {
	taskBoardLocations = {
	-- Eriador starts here
		["Gondamon"] = { loc="20.5s,97.0w", zone="EL", checked=true },
		["Hobbitebourg"] = { loc="31.3s,71.2w", zone="CO", checked=true },
		["Bree"] = { loc="30.2s,51.1w", zone="PB", rep="MB", checked=true },

		["Auberge abandonnée"] = { loc="34.0s,40.7w", zone="TS", checked=true },
		["Ost Guruth"] = { loc="31.4s,29.6w", zone="TS", checked=true},
		["Agamaur"] = { loc="29.6s,27.3w", zone="TS", checked=true },

		["Pont-à-Tréteaux"] = { loc="18.1s,53.8w", zone="HN", checked=true },
		["Amon Raith"] = { loc="12.5s,52.8w", zone="HN", checked=true },
		["Meluinen"] = { loc="13.7s,44.6w", zone="HN", checked=true },
		["Othrikar"] = { loc="7.1s,45.0w", zone="HN", checked=true },
		["Esteldin"] = { loc="9.7s,41.9w", zone="HN", checked=true },

		["Castelorge"] = { loc="23.3s,67.4w", zone="EV", checked=true },
		["Tinnudir"] = { loc="12.6s,67.2w", zone="EV", checked=true },
		["Ost Forod"] = { loc="8.1s,64.2w", zone="EV", checked=true },
		["Echad Garthadir"] = { loc="19.1s,71.0w", zone="EV", checked=true },

		["Camp de Barachen"] = { loc="34.0s,20.2w", zone="TT", checked=true },
		["Thorenhad"] = { loc="31.6s,15.0w", zone="TT", checked=true },
		["Echad Candelleth"] = { loc="37.0s,14.2w", zone="TT", checked=true },

		["Camp de Gloin"] = { loc="24.7s,4.1w", zone="MB", checked=true },
		["Hautes Falaises"] = { loc="24.6s,1.3e", zone="MB", checked=true },
		["Hrimbarg"] = { loc="24.5s,7.0e", zone="MB", checked=true },

		["Kauppa-kohta"] = { loc="2.6n,58.0w", zone="FO", checked=true },
		["Pynti-peldot"] = { loc="11.4n,69.6w", zone="FO", checked=true },
		["Zigilgund"] = { loc="9.6n,80.8w", zone="FO", checked=true },
		["Suri-kyla"] = { loc="19.0n,70.8w", zone="FO", checked=true },

		["Aughaire"] = { loc="0.0n,39.8w", zone="AN", checked=true },
		["Tyrn Lhuig"] = { loc="1.7s,33.4w", zone="AN", checked=true },
		["Gabilshathur"] = { loc="3.6s,26.5w", zone="AN", checked=true },
		["Gath Forthnir"] = { loc="10.4n,24.1w", zone="AN", checked=true },

		["Gwingris"] = { loc="40.2s,16.0w", zone="ER", checked=true },
		["Echad Mirobel"] = { loc="52.2s,17.0w", zone="ER", checked=true },
		["Echad Dunann"] = { loc="50.6s,8.0w", zone="ER", checked=true },

		["Lhan Tarren"] = { loc="75.3s,22.7w", zone="PD", checked=true },
		["Galtrev"] = { loc="80.1s,16.6w", zone="PD", checked=true },
		["Avardin"] = { loc="83.4s,20.6w", zone="PD", checked=true },
		["Barnavon"] = { loc="84.9s,16.5w", zone="PD", checked=true },
		["Lhan Rhos"] = { loc="87.1s,23.2W", zone="PD", checked=true },
        ["Camp d'éclaireurs rohirrim"] = { loc="81.0s,10.6w", zone="PD", checked=true },

		["Brondavant"] = { loc="86.9s,7.4w", zone="TR", checked=true },
		["Camp de Grimbold"] = { loc="87.8s,3.9w", zone="TR", checked=true },

	-- Rhovanion starts here
		["Belvédère Enfoui"] = { loc="8.5s,112.4w", zone="MO", checked=true },
		["Longue Descente"] = { loc="9.8s,112.7w", zone="MO", checked=true },
		["Cellier Putride"] = { loc="15.2s,111.7w", zone="MO", checked=true },
		["Salle de la Croisée des Chemins"] = { loc="5.2s,111.9w", zone="MO", checked=true },
		["Jazargund"] = { loc="4.0s,105.9w", zone="MO", checked=true },

		["Vingt et unième salle"] = { loc="6.3s,105.3w", zone="MO", checked=true },
		["Guet de l'Orque"] = { loc="11.2s,106.9w", zone="MO", checked=true },
		["Anazarmekhem"] = { loc="13.5s,108.1w", zone="MO", checked=true },
		["Refuge des Ombres"] = { loc="13.0s,101.6w", zone="MO", checked=true },
		["Première salle"] = { loc="8.1s,95.3w", zone="MO", checked=true },

		["Haldirith"] = { loc="21.4s,63.6w", zone="GF", checked=true },
		["Stangarde"] = { loc="25.4s,63.3w", zone="GF", checked=true },
		["Cuthstan"] = { loc="25.8s,65.9w", zone="GF", checked=true },
		["Poste de garde de Limeclaire"] = { loc="25.5s,67.1w", zone="GF", checked=true },
		["Parth Célébrant"] = { loc="26.6s,58.2w", zone="GF", checked=true },
		["Camp d'Aculf"] = { loc="39.1s,55.3w", zone="GF", checked=true },
		["Etheburg"] = { loc="31.4s,52.1w", zone="GF", checked=true },

		["Langhold"] = { loc="35.9s,53.6w", zone="RE", checked=true },
		["Harwick"] = { loc="40.2s,52.0w", zone="RE", checked=true },
		["Coudeflots"] = { loc="45.7s,48.0w", zone="RE", checked=true },
		["Cliving"] = { loc="43.3s,56.5w", zone="RE", checked=true },
		["Elthengels"] = { loc="48.6s,52.6w", zone="RE", checked=true },
		["Eaworth"] = { loc="47.6s,64.0w", zone="RE", checked=true },
		["Faldham"] = { loc="54.5s,57.4w", zone="RE", checked=true },
		["Garsfeld"] = { loc="54.9s,61.7w", zone="RE", checked=true },
		["Rangeval"] = { loc="62.3s,54.2w", zone="RE", checked=true },
		["Neigebronne"] = { loc="60.5s,62.3w", zone="RE", checked=true },

		["Forloi"] = { loc="39.3s,60.9w", zone="LF", checked=true },

		["Aldburg"] = { loc="69.0s,64.5w", zone="RO", checked=true },
		["Veillefeu"] = { loc="69.5s,56.9w", zone="RO", checked=true },
		["Gué d'Ent"] = { loc="56.2s,65.8w", zone="RO", checked=true },
		["Oserley"] = { loc="45.4s,67.1w", zone="RO", checked=true },
		["Torrepont"] = { loc="50.8s,77.7w", zone="RO", checked=true },
		["Gapholt"] = { loc="53.7s,84.1w", zone="RO", checked=true },
		["Tertrebois"] = { loc="47.4s,80.0w", zone="RO", checked=true },
		["Gouffre de Helm"] = { loc="63.8s,89.5w", zone="RO", checked=true },
		["Fenmarche"] = { loc="66.7s,57.2w", zone="RO", checked=true },
        ["Sousharrow"] = { loc="67.4s,73.7w", zone="RO", checked=true },
        ["Edoras"] = { loc="60.7s,74.2w", zone="RO", checked=true },
        ["Bourgmitan"] = { loc="53.5s,72.9w", zone="RO", checked=true },
        ["Stoke"] = { loc="49.1s,69.5w", zone="RO", checked=true },
		["Grimslade"] = { loc="62.5s,82.1w", zone="RO", checked=true },

		["Dale"] = { loc="24.0n,26.2w", zone="BNO", checked=true },
        ["Erebor"] = { loc="29.1n,25.6w", zone="BNO", checked=true },
        ["Felegoth"] = { loc="47.7n,127.2w", zone="BNO", checked=true },

        ["Dom Goru"] = { loc="33.0n,38.5w", zone="BNA", checked=true },
        ["Martelieu"] = { loc="30.9n,12.2w", zone="BNA", checked=true },
        ["Jarnfast"] = { loc="28.4n,3.7w", zone="BNA", checked=true },
        ["Skarhald"] = { loc="34.7n,45.4w", zone="BNA", checked=true },

		["Arhaim"] = { loc="5.7s,61.0w", zone="VAN", checked=true },
        ["Beorninghus"] = { loc="13.3n,53.3w", zone="VAN", checked=true },
        ["Blomgard"] = { loc="1.6s,55.3w", zone="VAN", checked=true },
        ["Hultvis"] = { loc="5.1n,55.0w", zone="VAN", checked=true },
        ["Vegbar"] = { loc="8.0n,58.6w", zone="VAN", checked=true },

        ["Limlok"] = { loc="20.9n,55.9w", zone="PLF", checked=true },
        ["Thokvist"] = { loc="26.0n,58.4w", zone="PLF", checked=true },

        ["Annâk-khurfu"] = { loc="32.8n,61.0w", zone="VAI", checked=true },
        ["Zarkul-sulun"] = { loc="100.7s,17.3w", zone="VAI", checked=true },
	-- Gondor starts here
		["Calembel"] = { loc="67.1s,55.9w", zone="WG", checked=true },
		["Dinadab"] = { loc="63.6s,59.1w", zone="WG", checked=true },
		["Dol Amroth"] = { loc="75.6s,72.2w", zone="WG", checked=true },
		["Morlad"] = { loc="56.9s,67.6w", zone="WG", checked=true },
		["Tadrent"] = { loc="74.1s,62.1w", zone="WG", checked=true },

		["Aerthir"] = { loc="83.9s,40.2w", zone="CG", checked=true },
		["Erynos"] = { loc="80.0s,32.8w", zone="CG", checked=true },
		["Ethring"] = { loc="71.8s,50.1w", zone="CG", checked=true },
		["Linhir"] = { loc="80.7s,45.5w", zone="CG", checked=true },
		["Malbarth"] = { loc="80.2s,42.3w", zone="CG", checked=true },
		["Ost Anglebed"] = { loc="79.2s,39.0w", zone="CG", checked=true },
		["Pelargir"] = { loc="83.0s,34.7w", zone="CG", checked=true },
		["Sarnhad"] = { loc="81.6s,43.9w", zone="CG", checked=true },

		["Glaniath"] = { loc="80.5s,29.8w", zone="EG", checked=true },
		["Tumladen"] = { loc="76.7s,29.6w", zone="EG", checked=true },
		["Arnach"] = { loc="76.6s,24.2w", zone="EG", checked=true },
		["Bar Hurin"] = { loc="73.3s,12.7w", zone="EG", checked=true },
		["Poste d'observation de Faramir"] = { loc="65.1s,6.2w", zone="EG", checked=true },
		["Imloth Melui"] = { loc="73.3s,23.7w", zone="EG", checked=true },

		["Minas Tirith"] = { loc="65.3s,16.7w", zone="AA", checked=true },
		["Crithost"] = { loc="54.1s,16.1w", zone="AA", checked=true },

		["Ost Rimmon"] = { loc="46.8s,35.4w", zone="LA", checked=true },
		["Monture de guerre des Hommes du Roi"] = { loc="45.3s,28.1w", zone="LA", checked=true },

		["Camp de l'armée"] = { loc="40.8s,10.3w", zone="LD", checked=true },
		["Haerondir"] = { loc="36.4s,8.8w", zone="LD", checked=true },

    -- Mordor starts here
		["Fort d'Udûn"] = { loc="41.4s,0.7w", zone="PG", checked=true },
		["Ruines de Dingarth"] = { loc="47.5s,8.8e", zone="PG", checked=true },
		["Magh Ashtu"] = { loc="53.1s,10.8e", zone="PG", checked=true },

		["Estolad Lan"] = { loc="64.6s,2.2w", zone="VM", checked=true },
	},

    factions = {
		XXX = "Aucune",
		AO  = "Armée de l'Ouest",
		CB  = "La Compagnie Blanche",
		CGO = "Conquête de Gorgoroth",
		CGR = "La Compagnie Grise",
		CN  = "Conseil du Nord",
		CR  = "Cavaliers du Rohan",
		CS  = "Les Cavaliers de Stangarde",
		CT  = "Cavaliers de Théodred",
		DA  = "Dol Amroth",
		DM  = "Défenseurs de Minas Tirith",
		EFE = "Elfes de Felegoth",
		EFO = "Elfes de Fondcombe",
		EG  = "Les Eglain",
		EO  = "Les Eorlingas",
		EMG = "Expédition des Montagnes Grises",
		GA  = "Les Gardiens d'Annuminas",
		HB  = "Hommes de Bree",
		HD  = "Hommes de Dale",
		HE  = "Les Helmingas",
		HGL = "Les Héros de la Gorge du Limeclair",
		HPD = "Hommes du pays de Dun",
		GF  = "Mineurs/Gardes de la Garnison de Fer",
		LF  = "Lossoth du Forochel",
		LGA = "La Grande Alliance",
		LRG = "Les Reconquérants de Gundabad",
		NE  = "Nains d'Erebor",
		PE  = "Pelargir",
		PLF = "Peuple des Landes Farouches",
		PS  = "Peuple Sauvage",
		PT  = "Palais de Thorin",
		PTS = "Protecteurs des Terres Sauvage",
		RE  = "Rôdeur d'Esteldin",
		RI  = "Rôdeurs de l'Ithilien",
		SM  = "La Société des Mathoms",
		ZZZ = "Indéfinie",
	},

    zones = {
		AA="Ancien Anorien",
		AN="Angmar",
		BNA="Les Bastions des Nains",
		BNO="Bastions du Nord",
		CG="Gondor Central",
		CO="La Comté",
		EG="Gondor Oriental",
		EL="Ered Luin",
		ER="Eregion",
		EV="Evendim",
		FO="Forochel",
		GF="Grand Fleuve",
		HN="Haut du Nord",
		LA="Lointain Anorien",
		LD="Landes Désertiques",
		LF="Landes Farouches",
		MB="Monts Brumeux",
		MO="Moria",
		PB="Pays de Bree",
		PD="Pays de Dun",
		PG="Plateau de Gorgoroth",
		PLF="Puits du Long Fleuve",
		RE="Rohan Est",
		RO="Rohan Ouest",
        TS="Terres Solitaires",
        TT="Trouée de Trolls",
		TR="Trouée du Rohan",
		VAI="Val d'Aïeul",
		VAN="Val d'Anduin",
		VM="Vallée de Morgul",
		WG="Gondor Occidental",
    },

	trophies = {

		--[""] = { Name="Aile duveteuse", TaskBoards = { ["Langhold"] = "XXX", ["Harwick"] = "XXX", ["Coudeflots"] = "XXX", ["Cliving"] = "XXX", ["Elthengels"] = "XXX", ["Eaworth"] = "XXX", ["Faldham"] = "XXX", ["Garsfeld"] = "XXX", ["Rangeval"] = "XXX", ["Neigebronne"] = "XXX" } },
		["0DB66"] = { Name="Aile énorme", TaskBoards = { ["Camp de Gloin"] = "PT", ["Hautes Falaises"] = "PT" } },
		--[""] = { Name="Aile fine", TaskBoards= { ["Aldburg"] = "EO", ["Veillefeu"] = "EO", ["Gué d'Ent"] = "EO", ["Oserley"] = "EO", ["Torrepont"] = "EO", ["Gapholt"] = "EO", ["Tertrebois"] = "EO", ["Gouffre de Helm"] = "EO", ["Fenmarche"] = "EO", ["Sousharrow"] = "EO", ["Edoras"] = "EO", ["Bourgmitan"] = "EO", ["Stoke"] = "EO", ["Grimslade"] = "EO" } },
		["0DB65"] = { Name="Aile lisse", TaskBoards = { ["Thorenhad"] = "EFO" } },
		["0DB61"] = { Name="Aile mate", TaskBoards = { ["Auberge abandonnée"] = "EG", ["Bree"] = "HB" } },
		["0DB68"] = { Name="Aile monstrueuse", TaskBoards = { ["Gwingris"] = "XXX", ["Echad Dunann"] = "XXX", ["Gath Forthnir"] = "CN" } },
		["30476"] = { Name="Aile pliée", TaskBoards = { ["Forloi"] = "PLF", ["Langhold"] = "XXX", ["Harwick"] = "XXX", ["Coudeflots"] = "XXX", ["Cliving"] = "XXX", ["Elthengels"] = "XXX", ["Eaworth"] = "XXX", ["Faldham"] = "XXX", ["Garsfeld"] = "XXX", ["Rangeval"] = "XXX", ["Neigebronne"] = "XXX" } },
		["0DEEA"] = { Name="Aile polie", TaskBoards = { ["Echad Mirobel"] = "XXX" } },
		["0DB6A"] = { Name="Aile sale", TaskBoards = { ["Gondamon"] = "PT", ["Hobbitebourg"] = "SM" } },
		["54D23"] = { Name="Aile sinistre", TaskBoards = { ["Limlok"] = "PLF", ["Thokvist"] = "PLF" } },
		--[""] = { Name="Aile taillée", TaskBoards= { ["Aldburg"] = "HE", ["Veillefeu"] = "HE", ["Gué d'Ent"] = "HE", ["Oserley"] = "HE", ["Torrepont"] = "HE", ["Gapholt"] = "HE", ["Tertrebois"] = "HE", ["Gouffre de Helm"] = "HE", ["Fenmarche"] = "HE", ["Sousharrow"] = "HE", ["Edoras"] = "HE", ["Bourgmitan"] = "HE", ["Stoke"] = "HE", ["Grimslade"] = "HE", ["Glaniath"] = "RI", ["Tumladen"] = "RI", ["Arnach"] = "RI", ["Bar Hurin"] = "RI", ["Poste d'observation de Faramir"] = "RI", ["Imloth Melui"] = "RI" } },
		["0F792"] = { Name="Arc court cassé", TaskBoards = { ["Castelorge"] = "SM", ["Tinnudir"] = "GA", ["Agamaur"] = "EG", ["Esteldin"] = "RE" } },
		["0F797"] = { Name="Arc long cassé", TaskBoards = { ["Echad Mirobel"] = "XXX" } },
		["0DC1F"] = { Name="Bec ébréché", TaskBoards = { ["Auberge abandonnée"] = "EG" } },
		["0DC28"] = { Name="Bec émoussé", TaskBoards = { ["Gondamon"] = "PT" } },
		--[""] = { Name="Bec épais", TaskBoards = { ["Langhold"] = "XXX", ["Harwick"] = "XXX", ["Coudeflots"] = "XXX", ["Cliving"] = "XXX", ["Elthengels"] = "XXX", ["Eaworth"] = "XXX", ["Faldham"] = "XXX", ["Garsfeld"] = "XXX", ["Rangeval"] = "XXX", ["Neigebronne"] = "XXX" } },
		["30473"] = { Name="Bec érodé", TaskBoards = { ["Forloi"] = "PLF", ["Langhold"] = "XXX", ["Harwick"] = "XXX", ["Coudeflots"] = "XXX", ["Cliving"] = "XXX", ["Elthengels"] = "XXX", ["Eaworth"] = "XXX", ["Faldham"] = "XXX", ["Garsfeld"] = "XXX", ["Rangeval"] = "XXX", ["Neigebronne"] = "XXX" } },
		["0DC24"] = { Name="Bec extrêmement aiguisé", TaskBoards = { ["Camp de Gloin"] = "PT", ["Hautes Falaises"] = "PT" } },
		["0DC21"] = { Name="Bec irrégulier", TaskBoards = { ["Othrikar"] = "PT", ["Auberge abandonnée"] = "EG", ["Esteldin"] = "RE", ["Pont-à-Tréteaux"] = "RE" } },
		-- [""] = { Name="Bec noirci", TaskBoards = { ["Aerthir"] = "PE", ["Erynos"] = "PE", ["Ethring"] = "PE", ["Linhir"] = "PE", ["Malbarth"] = "PE", ["Ost Anglebed"] = "PE", ["Pelargir"] = "PE", ["Sarnhad"] = "PE" } },
		["54D5D"] = { Name="Bec sauvage", TaskBoards= { ["Annâk-khurfu"] = "LRG", ["Zarkul-sulun"] = "LRG" } },
		["0DC23"] = { Name="Bec très aiguisé", TaskBoards = { ["Thorenhad"] = "EFO" } },
		["0DB1C"] = { Name="Belle fourrure", TaskBoards = { ["Ost Forod"] = "XXX", ["Camp de Barachen"] = "PT", ["Thorenhad"] = "EFO" } },
		["0DCC1"] = { Name="Belle peau", TaskBoards = { ["Ost Forod"] ="XXX", ["Camp de Barachen"] = "PT", ["Thorenhad"] = "EFO", ["Echad Candelleth"] = "EFO" } },
		["0DBCB"] = { Name="Belle plume", TaskBoards = { ["Thorenhad"] = "EFO" } },
		["27710"] = { Name="Bouclier troué", TaskBoards = { ["Camp de Grimbold"] = "CT", ["Brondavant"] = "CT", ["Camp d'éclaireurs rohirrim"] = "CT", ["Haldirith"] = "CS", ["Stangarde"] = "CS", ["Cuthstan"] = "CS", ["Poste de garde de Limeclaire"] = "CS", ["Parth Célébrant"] = "CS", ["Camp d'Aculf"] = "CS", ["Etheburg"] = "CS", ["Langhold"] = "XXX", ["Harwick"] = "XXX", ["Coudeflots"] = "XXX", ["Cliving"] = "XXX", ["Elthengels"] = "XXX", ["Eaworth"] = "XXX", ["Faldham"] = "XXX", ["Garsfeld"] = "XXX", ["Rangeval"] = "XXX", ["Neigebronne"] = "XXX" } },
		--[""] = { Name="Branche fendue", TaskBoards = { ["Langhold"] = "XXX", ["Harwick"] = "XXX", ["Coudeflots"] = "XXX", ["Cliving"] = "XXX", ["Elthengels"] = "XXX", ["Eaworth"] = "XXX", ["Faldham"] = "XXX", ["Garsfeld"] = "XXX", ["Rangeval"] = "XXX", ["Neigebronne"] = "XXX" } },
		["30478"] = { Name="Branche moussue", TaskBoards = { ["Forloi"] = "PLF" } },
		["54D43"] = { Name="Branche noircie", TaskBoards = { ["Limlok"] = "PTS", ["Thokvist"] = "PTS" } },
		["0DC2D"] = { Name="Branche noueuse", TaskBoards = { ["Thorenhad"] = "EFO" } },
		["4B976"] = { Name="Branche pétrifiée", TaskBoards = { ["Dale"] = "EFE", ["Erebor"] = "EFE", ["Felegoth"] = "EFE" } },
		["0DC30"] = { Name="Branche puissante", TaskBoards = { ["Gwingris"] = "XXX" } },
		["0DC2B"] = { Name="Branche rigide", TaskBoards = { ["Agamaur"] = "EG" } },
		["0DC2C"] = { Name="Branche tordue", TaskBoards = { ["Agamaur"] = "EG" } },
		["30481"] = { Name="Cape arrachée", TaskBoards = { ["Forloi"] = "PLF", ["Langhold"] = "XXX", ["Harwick"] = "XXX", ["Coudeflots"] = "XXX", ["Cliving"] = "XXX", ["Elthengels"] = "XXX", ["Eaworth"] = "XXX", ["Faldham"] = "XXX", ["Garsfeld"] = "XXX", ["Rangeval"] = "XXX", ["Neigebronne"] = "XXX" } },
		["4B965"] = { Name="Carapace à épines", TaskBoards = { ["Dale"] = "HD", ["Erebor"] = "HD", ["Felegoth"] = "HD" } },
		["0DC44"] = { Name="Carapace agrandie", TaskBoards = { ["Tyrn Lhuig"] = "XXX" } },
		["4F702"] = { Name="Carapace calcifiée", TaskBoards = { ["Arhaim"] = "PS", ["Beorninghus"] = "PS", ["Blomgard"] = "PS", ["Hultvis"] = "PS", ["Vegbar"] = "PS" } },
		["0DC42"] = { Name="Carapace durcie", TaskBoards = { ["Echad Candelleth"] = "EFO", ["Thorenhad"] = "EFO" } },
		["0DC47"] = { Name="Carapace légère", TaskBoards = { ["Gondamon"] = "PT", ["Hobbitebourg"] = "SM" } },
		["0DC41"] = { Name="Carapace lourde", TaskBoards = { ["Castelorge"] = "SM", ["Tinnudir"] = "GA", ["Agamaur"] = "EG" } },
		--[""] = { Name="Carapace luisante", TaskBoards = { ["Aerthir"] = "PE", ["Erynos"] = "PE", ["Ethring"] = "PE", ["Linhir"] = "PE", ["Malbarth"] = "PE", ["Ost Anglebed"] = "PE", ["Pelargir"] = "PE", ["Sarnhad"] = "PE", ["Minas Tirith"] = "DM", ["Crithost"] = "DM" } },
		["0DC3D"] = { Name="Carapace moussue", TaskBoards = { ["Bree"] = "HB" } },
		["0DC3E"] = { Name="Carapace noircie", TaskBoards = { ["Bree"] = "HB" } },
		--[""] = { Name="Carapace prismatique", TaskBoards = { ["Camp de l'armée"] = "AO", ["Haerondir"] = "AO" } },
		["0DC43"] = { Name="Carapace raffermie", TaskBoards = { ["Hautes Falaises"] = "PT", ["Camp de Gloin"] = "PT", ["Aughaire"] = "XXX" } },
		["0DC40"] = { Name="Carapace rigide", TaskBoards = { ["Meluinen"] ="EFO", ["Esteldin"] = "RE", ["Auberge abandonnée"] = "EG", ["Ost Guruth"] = "EG" } },
		["0DC45"] = { Name="Carapace renforcée", TaskBoards = { ["Gath Forthnir"] = "CN", ["Gwingris"] = "XXX" } },
		--[""] = { Name="Carapace teintée", TaskBoards = { ["Langhold"] = "XXX", ["Harwick"] = "XXX", ["Coudeflots"] = "XXX", ["Cliving"] = "XXX", ["Elthengels"] = "XXX", ["Eaworth"] = "XXX", ["Faldham"] = "XXX", ["Garsfeld"] = "XXX", ["Rangeval"] = "XXX", ["Neigebronne"] = "XXX" } },
		--[""] = { Name="Carapace vitreuse", TaskBoards = { ["Camp de Grimbold"] = "CT", ["Haldirith"] = "CS", ["Stangarde"] = "CS", ["Cuthstan"] = "CS", ["Poste de garde de Limeclaire"] = "CS", ["Parth Célébrant"] = "CS", ["Camp d'Aculf"] = "CS", ["Etheburg"] = "CS" } },
		["0DFC3"] = { Name="Charmant fourreau d'épée", TaskBoards = { ["Belvédère Enfoui"] = "GF", ["Longue Descente"] = "GF", ["Cellier Putride"] = "GF", ["Salle de la Croisée des Chemins"] = "GF", ["Jazargund"] = "GF" } },
		["4B963"] = { Name="Cimeterre rouillé", TaskBoards = { ["Dale"] = "NE", ["Erebor"] = "NE", ["Felegoth"] = "NE" } },
		["3A72A"] = { Name="Dague brisée", TaskBoards= { ["Aldburg"] = "EO", ["Veillefeu"] = "EO", ["Gué d'Ent"] = "EO", ["Oserley"] = "EO", ["Torrepont"] = "EO", ["Gapholt"] = "EO", ["Tertrebois"] = "EO", ["Gouffre de Helm"] = "EO", ["Fenmarche"] = "EO", ["Sousharrow"] = "EO", ["Edoras"] = "EO", ["Bourgmitan"] = "EO", ["Stoke"] = "EO", ["Grimslade"] = "EO" } },
		["0F79E"] = { Name="Dague cassée", TaskBoards = { ["Gondamon"] = "PT", ["Hobbitebourg"] = "SM" } },
		["0DD53"] = { Name="Duramen entaillé", TaskBoards = { ["Agamaur"] = "EG", ["Meluinen"] = "EFO" } },
		["0DD55"] = { Name="Duramen gris", TaskBoards = { ["Thorenhad"] = "EFO" } },
		["0DD58"] = { Name="Duramen monstrueux", TaskBoards = { ["Gwingris"] = "XXX" } },
		["0DD54"] = { Name="Duramen noir", TaskBoards = { ["Agamaur"] = "EG" } },
		--[""] = { Name="Duramen noueux", TaskBoards = { ["Haldirith"] = "HGL", ["Stangarde"] = "HGL", ["Cuthstan"] = "HGL", ["Poste de garde de Limeclaire"] = "HGL", ["Parth Célébrant"] = "HGL", ["Camp d'Aculf"] = "HGL", ["Etheburg"] = "HGL" } },
		--[""] = { Name="Écaille aiguisée", TaskBoards = { ["Langhold"] = "XXX", ["Harwick"] = "XXX", ["Coudeflots"] = "XXX", ["Cliving"] = "XXX", ["Elthengels"] = "XXX", ["Eaworth"] = "XXX", ["Faldham"] = "XXX", ["Garsfeld"] = "XXX", ["Rangeval"] = "XXX", ["Neigebronne"] = "XXX" } },
		["0DB25"] = { Name="Écaille bosselée", TaskBoards = { ["Esteldin"] = "RE" } },
		["54D5A"] = { Name="Écaille d'onyx", TaskBoards = { ["Annâk-khurfu"] = "LRG", ["Zarkul-sulun"] = "LRG" } },
		["0DEC8"] = { Name="Écaille élégante", TaskBoards = { ["Vingt et unième salle"] = "GF", ["Guet de l'Orque"] = "GF", ["Anazarmekhem"] = "GF", ["Refuge des Ombres"] = "GF", ["Première salle"] = "GF" } },
		["0DB27"] = { Name="Ecaille énorme", TaskBoards = { ["Camp de Gloin"] = "PT", ["Hautes Falaises"] = "PT" } },
		["0DB28"] = { Name="Ecaille impressionnante", TaskBoards = { ["Zigilgund"] = "XXX", ["Suri-kyla"] = "LF" } },
		["0DB26"] = { Name="Ecaille lisse", TaskBoards = { ["Echad Candelleth"] = "EFO" } },
		["0DEC6"] = { Name="Écaille polie", TaskBoards = { ["Belvédère Enfoui"] = "GF", ["Longue Descente"] = "GF", ["Cellier Putride"] = "GF", ["Salle de la Croisée des Chemins"] = "GF", ["Jazargund"] = "GF" } },
		--[""] = { Name="Écaille prismatique", TaskBoards = { ["Camp de Grimbold"] = "CT", ["Haldirith"] = "CS", ["Stangarde"] = "CS", ["Cuthstan"] = "CS", ["Poste de garde de Limeclaire"] = "CS", ["Parth Célébrant"] = "CS", ["Camp d'Aculf"] = "CS", ["Etheburg"] = "CS" } },
		["4B967"] = { Name="Éclat d'obsidienne", TaskBoards = { ["Fort d'Udûn"] = "CGO", ["Ruines de Dingarth"] = "CGO", ["Magh Ashtu"] = "CGO" } },
		["0DD56"] = { Name="Enorme duramen", TaskBoards = { ["Camp de Gloin"] = "PT", ["Hautes Falaises"] = "PT" } },
			["0DBAD"] = { Name="Énorme sécrétion", TaskBoards = { ["Aughaire"] = "XXX" } },
		["0F793"] = { Name="Epée longue cassée", TaskBoards = { ["Tinnudir"] = "GA", ["Ost Forod"] = "XXX", ["Camp de Barachen"] = "PT", ["Thorenhad"] = "EFO", ["Echad Candelleth"]  = "EFO" } },
		["0DB97"] = { Name="Essence chatoyante", TaskBoards = { ["Tinnudir"] = "GA", ["Agamaur"] = "EG" } },
		--[""] = { Name="Essence évanescente", TaskBoards = { ["Camp de Grimbold"] = "CT", ["Haldirith"] = "CS", ["Stangarde"] = "CS", ["Cuthstan"] = "CS", ["Poste de garde de Limeclaire"] = "CS", ["Parth Célébrant"] = "CS", ["Camp d'Aculf"] = "CS", ["Etheburg"] = "CS" } },
		["0DB96"] = { Name="Essence irisée", TaskBoards = { ["Ost Guruth"] = "EG", ["Amon Raith"] = "RE" } },
		["0DB94"] = { Name="Essence moirée", TaskBoards = { ["Bree"] = "HB" } },
		["4F704"] = { Name="Essence perdue", TaskBoards = { ["Arhaim"] = "PS", ["Beorninghus"] = "PS", ["Blomgard"] = "PS", ["Hultvis"] = "PS", ["Vegbar"] = "PS" } },
		["4B966"] = { Name="Étrange saleté", TaskBoards = { ["Fort d'Udûn"] = "CGO", ["Ruines de Dingarth"] = "CGO", ["Magh Ashtu"] = "CGO" } },
		["4B973"] = { Name="Étrange sécrétion", TaskBoards = { ["Fort d'Udûn"] = "CGO", ["Ruines de Dingarth"] = "CGO", ["Magh Ashtu"] = "CGO" } },
		["0DCCE"] = { Name="Fourreau d'épée à dorures", TaskBoards = { ["Zigilgund"] = "XXX", ["Hrimbarg"] = "PT", ["Kauppa-kohta"] = "LF", ["Tyrn Lhuig"] = "XXX", ["Gabilshathur"] = "XXX", ["Pynti-peldot"] = "LF", ["Aughaire"] = "XXX" } },
		["54D4B"] = { Name="Fourreau d'épée ancienne", TaskBoards = { ["Limlok"] = "PTS", ["Thokvist"] = "PTS" } },
		["0DCD1"] = { Name="Fourreau d'épée cassé", TaskBoards = { ["Gondamon"] = "PT", ["Hobbitebourg"] = "SM" } },
		["0DCCD"] = { Name="Fourreau d'épée clouté", TaskBoards = { ["Aughaire"] = "XXX", ["Camp de Gloin"] = "PT", ["Hautes Falaises"] = "PT", ["Echad Garthadir"] = "GA" } },
		["27724"] = { Name="Fourreau d'épée décoratif", TaskBoards = { ["Camp de Grimbold"] = "CT", ["Brondavant"] = "CT", ["Camp d'éclaireurs rohirrim"] = "CT", ["Haldirith"] = "CS", ["Stangarde"] = "CS", ["Cuthstan"] = "CS", ["Poste de garde de Limeclaire"] = "CS", ["Parth Célébrant"] = "CS", ["Camp d'Aculf"] = "CS", ["Etheburg"] = "CS", ["Langhold"] = "XXX", ["Harwick"] = "XXX", ["Coudeflots"] = "XXX", ["Cliving"] = "XXX", ["Elthengels"] = "XXX", ["Eaworth"] = "XXX", ["Faldham"] = "XXX", ["Garsfeld"] = "XXX", ["Rangeval"] = "XXX", ["Neigebronne"] = "XXX" } },
		["4F6F9"] = { Name="Fourreau d'épée des nains", TaskBoards= { ["Dom Goru"] = "EMG", ["Martelieu"] = "EMG", ["Jarnfast"] = "EMG", ["Skarhald"] = "EMG" } },
		["0DFC4"] = { Name="Fourreau d'épée élégant", TaskBoards = { ["Vingt et unième salle"] = "GF", ["Guet de l'Orque"] = "GF", ["Anazarmekhem"] = "GF", ["Refuge des Ombres"] = "GF", ["Première salle"] = "GF" } },
		["3F1E9"] = { Name="Fourreau d'épée elfique", TaskBoards = { ["Ost Rimmon"] = "CR", ["Monture de guerre des Hommes du Roi"] = "CR" } },
		["27721"] = { Name="Fourreau d'épée en métal", TaskBoards = { ["Galtrev"] = "HPD", ["Lhan Tarren"] = "HPD", ["Avardin"] = "HPD", ["Barnavon"] = "HPD", ["Lhan Rhos"] = "HPD" } },
		["3A799"] = { Name="Fourreau d'épée étincelant", TaskBoards= { ["Aldburg"] = "EO", ["Veillefeu"] = "EO", ["Gué d'Ent"] = "EO", ["Oserley"] = "EO", ["Torrepont"] = "EO", ["Gapholt"] = "EO", ["Tertrebois"] = "EO", ["Gouffre de Helm"] = "EO", ["Fenmarche"] = "EO", ["Sousharrow"] = "EO", ["Edoras"] = "EO", ["Bourgmitan"] = "EO", ["Stoke"] = "EO", ["Grimslade"] = "EO" } },
		["3A797"] = { Name="Fourreau d'épée grêlé", TaskBoards= { ["Aldburg"] = "HE", ["Veillefeu"] = "HE", ["Gué d'Ent"] = "HE", ["Oserley"] = "HE", ["Torrepont"] = "HE", ["Gapholt"] = "HE", ["Tertrebois"] = "HE", ["Gouffre de Helm"] = "HE", ["Fenmarche"] = "HE", ["Sousharrow"] = "HE", ["Edoras"] = "HE", ["Bourgmitan"] = "HE", ["Stoke"] = "HE", ["Grimslade"] = "HE", ["Calembel"] = "DA", ["Dinadab"] = "DA", ["Dol Amroth"] = "DA", ["Morlad"] = "DA", ["Tadrent"] = "DA", ["Aerthir"] = "PE", ["Erynos"] = "PE", ["Ethring"] = "PE", ["Linhir"] = "PE", ["Malbarth"] = "PE", ["Ost Anglebed"] = "PE", ["Pelargir"] = "PE", ["Sarnhad"] = "PE", ["Glaniath"] = "RI", ["Tumladen"] = "RI", ["Arnach"] = "RI", ["Bar Hurin"] = "RI", ["Poste d'observation de Faramir"] = "RI", ["Imloth Melui"] = "RI", ["Minas Tirith"] = "DM", ["Crithost"] = "DM" } },
		["0DFC5"] = { Name="Fourreau d'épée harmonieux", TaskBoards = { ["Vingt et unième salle"] = "GF", ["Guet de l'Orque"] = "GF", ["Anazarmekhem"] = "GF", ["Refuge des Ombres"] = "GF", ["Première salle"] = "GF" } },
		["0DCCB"] = { Name="Fourreau d'épée lourd", TaskBoards = { ["Castelorge"] = "SM", ["Tinnudir"] = "GA", ["Agamaur"] = "EG", ["Esteldin"] = "RE" } },
		["0DCCC"] = { Name="Fourreau d'épée neuf", TaskBoards = { ["Ost Forod"] = "XXX", ["Camp de Barachen"] = "PT", ["Echad Candelleth"] = "EFO" } },
		["0DCC8"] = { Name="Fourreau d'épée noirci", TaskBoards = { ["Auberge abandonnée"] = "EG", ["Bree"] = "HB" } },
		["30489"] = { Name="Fourreau d'épée orné", TaskBoards = { ["Forloi"] = "PLF", ["Langhold"] = "XXX", ["Harwick"] = "XXX", ["Coudeflots"] = "XXX", ["Cliving"] = "XXX", ["Elthengels"] = "XXX", ["Eaworth"] = "XXX", ["Faldham"] = "XXX", ["Garsfeld"] = "XXX", ["Rangeval"] = "XXX", ["Neigebronne"] = "XXX" } },
		["0DFC2"] = { Name="Fourreau d'épée poli", TaskBoards = { ["Belvédère Enfoui"] = "GF", ["Longue Descente"] = "GF", ["Cellier Putride"] = "GF", ["Salle de la Croisée des Chemins"] = "GF", ["Jazargund"] = "GF" } },
		["0DCCA"] = { Name="Fourreau d'épée rigide", TaskBoards = { ["Ost Guruth"] = "EG", ["Pont-à-Tréteaux"] = "HB", ["Amon Raith"] = "RE", ["Meluinen"] = "EFO", ["Othrikar"] = "PT" } },
		["0DCCF"] = { Name="Fourreau d'épée serti de gemmes", TaskBoards = { ["Echad Mirobel"] = "XXX", ["Echad Dunann"] = "XXX", ["Gath Forthnir"] = "CN" } },
		["0DCC7"] = { Name="Fourreau d'épée usé", TaskBoards = { ["Bree"] = "HB" } },
		--[""] = { Name="Fourreau d'épée terni", TaskBoards = { ["Langhold"] = "XXX", ["Harwick"] = "XXX", ["Coudeflots"] = "XXX", ["Cliving"] = "XXX", ["Elthengels"] = "XXX", ["Eaworth"] = "XXX", ["Faldham"] = "XXX", ["Garsfeld"] = "XXX", ["Rangeval"] = "XXX", ["Neigebronne"] = "XXX" } },
		["3A752"] = { Name="Fourrure abîmée", TaskBoards= { ["Aldburg"] = "HE", ["Veillefeu"] = "HE", ["Gué d'Ent"] = "HE", ["Oserley"] = "HE", ["Torrepont"] = "HE", ["Gapholt"] = "HE", ["Tertrebois"] = "HE", ["Gouffre de Helm"] = "HE", ["Fenmarche"] = "HE", ["Sousharrow"] = "HE", ["Edoras"] = "HE", ["Bourgmitan"] = "HE", ["Stoke"] = "HE", ["Grimslade"] = "HE", ["Calembel"] = "DA", ["Dinadab"] = "DA", ["Dol Amroth"] = "DA", ["Morlad"] = "DA", ["Tadrent"] = "DA", ["Aerthir"] = "PE", ["Erynos"] = "PE", ["Ethring"] = "PE", ["Linhir"] = "PE", ["Malbarth"] = "PE", ["Ost Anglebed"] = "PE", ["Pelargir"] = "PE", ["Sarnhad"] = "PE", ["Glaniath"] = "RI", ["Tumladen"] = "RI", ["Arnach"] = "RI", ["Bar Hurin"] = "RI", ["Poste d'observation de Faramir"] = "RI", ["Imloth Melui"] = "RI" } },
		["0DB1F"] = { Name="Fourrure albinos", TaskBoards = { ["Suri-kyla"] = "LF", ["Echad Dunann"] = "XXX", ["Echad Mirobel"] = "XXX", ["Gwingris"] = "XXX" } },
		["0DB1E"] = { Name="Fourrure d'un noir pur", TaskBoards = { ["Zigilgund"] = "XXX", ["Hrimbarg"] = "PT", ["Pynti-peldot"] = "LF", ["Kauppa-kohta"] = "LF", ["Gabilshathur"] = "XXX", ["Aughaire"] = "XXX" } },
		--[""] = { Name="Fourrure en lambeaux", TaskBoards= { ["Aldburg"] = "EO", ["Veillefeu"] = "EO", ["Gué d'Ent"] = "EO", ["Oserley"] = "EO", ["Torrepont"] = "EO", ["Gapholt"] = "EO", ["Tertrebois"] = "EO", ["Gouffre de Helm"] = "EO", ["Fenmarche"] = "EO", ["Sousharrow"] = "EO", ["Edoras"] = "EO", ["Bourgmitan"] = "EO", ["Stoke"] = "EO", ["Grimslade"] = "EO" } },
		["0DB21"] = { Name="Fourrure feutrée", TaskBoards = { ["Gondamon"] = "PT", ["Hobbitebourg"] = "SM" } },
		["4B96B"] = { Name="Fourrure hérissée", TaskBoards = { ["Dale"] = "EFE", ["Erebor"] = "EFE", ["Felegoth"] = "EFE" } },
		["0DB1D"] = { Name="Fourrure lustrée", TaskBoards = { ["Aughaire"] = "XXX", ["Camp de Gloin"] = "PT", ["Hautes Falaises"] = "PT" } },
		["2770C"] = { Name="Fourrure marquée", TaskBoards = { ["Camp de Grimbold"] = "CT", ["Brondavant"] = "CT", ["Camp d'éclaireurs rohirrim"] = "CT", ["Haldirith"] = "CS", ["Stangarde"] = "CS", ["Cuthstan"] = "CS", ["Poste de garde de Limeclaire"] = "CS", ["Parth Célébrant"] = "CS", ["Camp d'Aculf"] = "CS", ["Etheburg"] = "CS", ["Langhold"] = "XXX", ["Harwick"] = "XXX", ["Coudeflots"] = "XXX", ["Cliving"] = "XXX", ["Elthengels"] = "XXX", ["Eaworth"] = "XXX", ["Faldham"] = "XXX", ["Garsfeld"] = "XXX", ["Rangeval"] = "XXX", ["Neigebronne"] = "XXX" } },
		["0DB17"] = { Name="Fourrure mouillée", TaskBoards = { ["Bree"] = "HB" } },
		["3048F"] = { Name="Fourrure négligée", TaskBoards = { ["Forloi"] = "PLF", ["Langhold"] = "XXX", ["Harwick"] = "XXX", ["Coudeflots"] = "XXX", ["Cliving"] = "XXX", ["Elthengels"] = "XXX", ["Eaworth"] = "XXX", ["Faldham"] = "XXX", ["Garsfeld"] = "XXX", ["Rangeval"] = "XXX", ["Neigebronne"] = "XXX" } },
		["0DB18"] = { Name="Fourrure noircie", TaskBoards = { ["Auberge abandonnée"] = "EG", ["Bree"] = "HB" } },
		["0DB1A"] = { Name="Fourrure rugueuse", TaskBoards = { ["Auberge abandonnée"] = "EG", ["Ost Guruth"] = "EG", ["Pont-à-Tréteaux"] = "HB", ["Amon Raith"] = "RE", ["Esteldin"] = "RE", ["Othrikar"] = "PT" } },
		--[""] = { Name="Fourrure soyeuse", TaskBoards = { ["Langhold"] = "XXX", ["Harwick"] = "XXX", ["Coudeflots"] = "XXX", ["Cliving"] = "XXX", ["Elthengels"] = "XXX", ["Eaworth"] = "XXX", ["Faldham"] = "XXX", ["Garsfeld"] = "XXX", ["Rangeval"] = "XXX", ["Neigebronne"] = "XXX" } },
		["0DB1B"] = { Name="Fourrure tannée", TaskBoards = { ["Castelorge"] = "SM", ["Tinnudir"] = "GA", ["Esteldin"] = "RE" } },
		["54D41"] = { Name="Fourrure touchée par la nuit", TaskBoards= { ["Estolad Lan"] = "CB" } },
		--[""] = { Name="Fourrure usée", TaskBoards = { ["Ost Rimmon"] = "CR", ["Monture de guerre des Hommes du Roi"] = "CR", ["Camp de l'armée"] = "AO", ["Haerondir"] = "AO" } },
		["4F6FC"] = { Name="Fourrure usée par la pierre", TaskBoards = { ["Arhaim"] = "PS", ["Beorninghus"] = "PS", ["Blomgard"] = "PS", ["Hultvis"] = "PS", ["Vegbar"] = "PS" } },
		--[""] = { Name="Gourdin brisé", TaskBoards = { ["Langhold"] = "XXX", ["Harwick"] = "XXX", ["Coudeflots"] = "XXX", ["Cliving"] = "XXX", ["Elthengels"] = "XXX", ["Eaworth"] = "XXX", ["Faldham"] = "XXX", ["Garsfeld"] = "XXX", ["Rangeval"] = "XXX", ["Neigebronne"] = "XXX" } },
		["0F796"] = { Name="Gourdin en bois cassé", TaskBoards = { ["Echad Mirobel"] = "XXX", ["Echad Dunann"] = "XXX", ["Gwingris"] = "XXX", ["Suri-kyla"] = "LF", ["Gath Forthnir"] = "CN" } },
		["0DB63"] = { Name="Grande aile", TaskBoards = { ["Auberge abandonnée"] = "EG", ["Othrikar"] = "PT", ["Esteldin"] = "RE", ["Pont-à-Tréteaux"] = "HB" } },
		["0F795"] = { Name="Grande épée cassée", TaskBoards = { ["Zigilgund"] = "XXX", ["Hrimbarg"] = "PT", ["Pynti-peldot"] = "LF", ["Kauppa-kohta"] = "LF", ["Aughaire"] = "XXX", ["Gabilshathur"] = "XXX" } },
		["0DAF4"] = { Name="Grande phalange", TaskBoards = { ["Ost Guruth"] = "EG" } },
		["0DAEA"] = { Name="Grande saleté", TaskBoards = { ["Meluinen"] = "EFO", ["Auberge abandonnée"] = "EG", ["Esteldin"] = "RE", ["Ost Guruth"] = "EG" } },
		--[""] = { Name="Griffe abîmée", TaskBoards = { ["Aerthir"] = "PE", ["Erynos"] = "PE", ["Ethring"] = "PE", ["Linhir"] = "PE", ["Malbarth"] = "PE", ["Ost Anglebed"] = "PE", ["Pelargir"] = "PE", ["Sarnhad"] = "PE", ["Minas Tirith"] = "DM", ["Crithost"] = "DM" } },
		["0DAE0"] = { Name="Griffe aiguisée", TaskBoards = { ["Meluinen"] = "EFO" } },
		["4F705"] = { Name="Griffe atrophiée", TaskBoards= { ["Dom Goru"] = "EMG", ["Martelieu"] = "EMG", ["Jarnfast"] = "EMG", ["Skarhald"] = "EMG" } },
		["0DEA2"] = { Name="Griffe barbelée", TaskBoards = { ["Belvédère Enfoui"] = "GF", ["Longue Descente"] = "GF", ["Cellier Putride"] = "GF", ["Salle de la Croisée des Chemins"] = "GF", ["Jazargund"] = "GF" } },
		["0DAE2"] = { Name="Griffe extrêmement aiguisée", TaskBoards = { ["Thorenhad"] = "EFO", ["Camp de Barachen"] = "PT", ["Echad Candelleth"] = "EFO" } },
		["0DADE"] = { Name="Griffe irrégulière", TaskBoards = { ["Bree"] = "HB" } },
		--[""] = { Name="Griffe mortelle", TaskBoards = { ["Dale"] = "HD", ["Erebor"] = "HD", ["Felegoth"] = "HD" } },
		["0DAE3"] = { Name="Griffe mortellement aiguisée", TaskBoards = { ["Tyrn Lhuig"] = "XXX", ["Aughaire"] = "XXX" } },
		["54D29"] = { Name="Griffe noircie", TaskBoards = { ["Annâk-khurfu"] = "LRG", ["Zarkul-sulun"] = "LRG" } },
		["0DEA4"] = { Name="Griffe ratissante", TaskBoards = { ["Vingt et unième salle"] = "GF", ["Guet de l'Orque"] = "GF", ["Anazarmekhem"] = "GF", ["Refuge des Ombres"] = "GF", ["Première salle"] = "GF" } },
		["0DAE7"] = { Name="Griffe tordue", TaskBoards = { ["Hobbitebourg"] = "SM" } },
		["0DAE4"] = { Name="Griffe très acérée", TaskBoards = { ["Gabilshathur"] = "XXX" } },
		["0DAE1"] = { Name="Griffe très aiguisée", TaskBoards = { ["Castelorge"] = "SM", ["Tinnudir"] = "GA" } },
		--[""] = { Name="Grosse branche", TaskBoards = { ["Haldirith"] = "HGL", ["Stangarde"] = "HGL", ["Cuthstan"] = "HGL", ["Poste de garde de Limeclaire"] = "HGL", ["Parth Célébrant"] = "HGL", ["Camp d'Aculf"] = "HGL", ["Etheburg"] = "HGL" } },
		["3A729"] = { Name="Hachette brisée", TaskBoards= { ["Aldburg"] = "HE", ["Veillefeu"] = "HE", ["Gué d'Ent"] = "HE", ["Oserley"] = "HE", ["Torrepont"] = "HE", ["Gapholt"] = "HE", ["Tertrebois"] = "HE", ["Gouffre de Helm"] = "HE", ["Fenmarche"] = "HE", ["Sousharrow"] = "HE", ["Edoras"] = "HE", ["Bourgmitan"] = "HE", ["Stoke"] = "HE", ["Grimslade"] = "HE", ["Calembel"] = "DA", ["Dinadab"] = "DA", ["Dol Amroth"] = "DA", ["Morlad"] = "DA", ["Tadrent"] = "DA", ["Aerthir"] = "PE", ["Erynos"] = "PE", ["Ethring"] = "PE", ["Linhir"] = "PE", ["Malbarth"] = "PE", ["Ost Anglebed"] = "PE", ["Pelargir"] = "PE", ["Sarnhad"] = "PE", ["Glaniath"] = "RI", ["Tumladen"] = "RI", ["Arnach"] = "RI", ["Bar Hurin"] = "RI", ["Poste d'observation de Faramir"] = "RI", ["Imloth Melui"] = "RI" } },
		["0F78E"] = { Name="Hachette cassée", TaskBoards = { ["Bree"] = "HB" } },
		["0F794"] = { Name="Hallebarde cassée", TaskBoards = { ["Aughaire"] = "XXX", ["Camp de Gloin"] = "PT", ["Hautes Falaises"] = "PT", ["Echad Garthadir"] = "GA", ["Tyrn Lhuig"] = "XXX" } },
		["3F1E1"] = { Name="Lance brisée", TaskBoards = { ["Ost Rimmon"] = "CR", ["Monture de guerre des Hommes du Roi"] = "CR" } },
		["0DF14"] = { Name="Lance ébréchée", TaskBoards = { ["Estolad Lan"] = "LGA" } },
		["0F791"] = { Name="Lance en bois cassée", TaskBoards = { ["Esteldin"] = "RE", ["Othrikar"] = "PT", ["Amon Raith"] = "RE", ["Meluinen"] = "EFO", ["Ost Guruth"] = "EG", ["Pont-à-Tréteaux"] = "HB" } },
		["0F78F"] = { Name="Masse en bois cassée", TaskBoards = { ["Auberge abandonnée"] = "EG", ["Bree"] = "HB" } },
		--[""] = { Name="Masse en métal tordu", TaskBoards = { ["Galtrev"] = "HPD", ["Lhan Tarren"] = "HPD", ["Avardin"] = "HPD", ["Barnavon"] = "HPD", ["Lhan Rhos"] = "HPD" } },
		["0DCAE"] = { Name="Membrane impressionnante", TaskBoards = { ["Gabilshathur"] = "XXX" } },
		["4F6F5"] = { Name="Oreille atrophiée", TaskBoards= { ["Dom Goru"] = "EMG", ["Martelieu"] = "EMG", ["Jarnfast"] = "EMG", ["Skarhald"] = "EMG" } },
		["3048C"] = { Name="Oreille abîmée", TaskBoards = { ["Forloi"] = "PLF" } },
		--[""] = { Name="Oreille brûlée", TaskBoards = { ["Ost Rimmon"] = "CR", ["Monture de guerre des Hommes du Roi"] = "CR", ["Camp de l'armée"] = "AO", ["Haerondir"] = "AO" } },
		--[""] = { Name="Oreille déformée", TaskBoards = { ["Langhold"] = "XXX", ["Harwick"] = "XXX", ["Coudeflots"] = "XXX", ["Cliving"] = "XXX", ["Elthengels"] = "XXX", ["Eaworth"] = "XXX", ["Faldham"] = "XXX", ["Garsfeld"] = "XXX", ["Rangeval"] = "XXX", ["Neigebronne"] = "XXX" } },
		["0DB84"] = { Name="Oreille énorme", TaskBoards = { ["Camp de Gloin"] = "PT", ["Hautes Falaises"] = "PT", ["Aughaire"] = "XXX" } },
		["0DB82"] = { Name="Oreille entaillée", TaskBoards = { ["Castelorge"] = "SM", ["Tinnudir"] = "GA", ["Esteldin"] = "RE" } },
		["0DB83"] = { Name="Oreille grise", TaskBoards = { ["Thorenhad"] = "EFO", ["Camp de Barachen"] = "PT" } },
		["0DB81"] = { Name="Oreille imparfaite", TaskBoards = { ["Esteldin"] = "RE", ["Ost Guruth"] = "EG", ["Pont-à-Tréteaux"] = "HB" } },
		["0DB85"] = { Name="Oreille impressionnante", TaskBoards = { ["Hrimbarg"] = "PT" } },
		["0DB80"] = { Name="Oreille mate", TaskBoards = { ["Bree"] = "HB" } },
		["0DB86"] = { Name="Oreille monstrueuse", TaskBoards = { ["Echad Dunann"] = "XXX", ["Suri-kyla"] = "LF" } },
		["27733"] = { Name="Oreille mouchetée", TaskBoards = { ["Camp de Grimbold"] = "CT", ["Brondavant"] = "CT", ["Camp d'éclaireurs rohirrim"] = "CT", ["Haldirith"] = "CS", ["Stangarde"] = "CS", ["Cuthstan"] = "CS", ["Poste de garde de Limeclaire"] = "CS", ["Parth Célébrant"] = "CS", ["Camp d'Aculf"] = "CS", ["Etheburg"] = "CS", ["Langhold"] = "XXX", ["Harwick"] = "XXX", ["Coudeflots"] = "XXX", ["Cliving"] = "XXX", ["Elthengels"] = "XXX", ["Eaworth"] = "XXX", ["Faldham"] = "XXX", ["Garsfeld"] = "XXX", ["Rangeval"] = "XXX", ["Neigebronne"] = "XXX" } },
		["4B972"] = { Name="Oreille mystérieuse" , TaskBoards = { ["Fort d'Udûn"] = "CGO", ["Ruines de Dingarth"] = "CGO", ["Magh Ashtu"] = "CGO" } },
		--[""] = { Name="Oreille ornée", TaskBoards= { ["Aldburg"] = "EO", ["Veillefeu"] = "EO", ["Gué d'Ent"] = "EO", ["Oserley"] = "EO", ["Torrepont"] = "EO", ["Gapholt"] = "EO", ["Tertrebois"] = "EO", ["Gouffre de Helm"] = "EO", ["Fenmarche"] = "EO", ["Sousharrow"] = "EO", ["Edoras"] = "EO", ["Bourgmitan"] = "EO", ["Stoke"] = "EO", ["Grimslade"] = "EO" } },
		["54D74"] = { Name="Oreille poilue", TaskBoards = { ["Estolad Lan"] = "CB",  ["Annâk-khurfu"] = "LRG", ["Zarkul-sulun"] = "LRG" } },
		["0DB88"] = { Name="Oreille sale", TaskBoards = { ["Hobbitebourg"] = "SM" } },
		["27720"] = { Name="Oreille tachetée", TaskBoards = { ["Galtrev"] = "HPD", ["Lhan Tarren"] = "HPD", ["Avardin"] = "HPD", ["Barnavon"] = "HPD", ["Lhan Rhos"] = "HPD" } },
		--[""] = { Name="Oreille taillée", TaskBoards= { ["Aldburg"] = "HE", ["Veillefeu"] = "HE", ["Gué d'Ent"] = "HE", ["Oserley"] = "HE", ["Torrepont"] = "HE", ["Gapholt"] = "HE", ["Tertrebois"] = "HE", ["Gouffre de Helm"] = "HE", ["Fenmarche"] = "HE", ["Sousharrow"] = "HE", ["Edoras"] = "HE", ["Bourgmitan"] = "HE", ["Stoke"] = "HE", ["Grimslade"] = "HE", ["Glaniath"] = "RI", ["Tumladen"] = "RI", ["Arnach"] = "RI", ["Bar Hurin"] = "RI", ["Poste d'observation de Faramir"] = "RI", ["Imloth Melui"] = "RI", ["Minas Tirith"] = "DM", ["Crithost"] = "DM" } },
		["0DCC4"] = { Name="Peau albinos", TaskBoards = { ["Echad Mirobel"] = "XXX", ["Echad Dunann"] = "XXX", ["Suri-kyla"] = "LF", ["Gath Forthnir"] = "CN" } },
		["0DCC2"] = { Name="Peau brillante", TaskBoards = { ["Camp de Gloin"] = "PT", ["Hautes Falaises"] = "PT", ["Aughaire"] = "XXX" } },
		["3A757"] = { Name="Peau déchirée", TaskBoards= { ["Aldburg"] = "HE", ["Veillefeu"] = "HE", ["Gué d'Ent"] = "HE", ["Oserley"] = "HE", ["Torrepont"] = "HE", ["Gapholt"] = "HE", ["Tertrebois"] = "HE", ["Gouffre de Helm"] = "HE", ["Fenmarche"] = "HE", ["Sousharrow"] = "HE", ["Edoras"] = "HE", ["Bourgmitan"] = "HE", ["Stoke"] = "HE", ["Grimslade"] = "HE", ["Calembel"] = "DA", ["Dinadab"] = "DA", ["Dol Amroth"] = "DA", ["Morlad"] = "DA", ["Tadrent"] = "DA", ["Aerthir"] = "PE", ["Erynos"] = "PE", ["Ethring"] = "PE", ["Linhir"] = "PE", ["Malbarth"] = "PE", ["Ost Anglebed"] = "PE", ["Pelargir"] = "PE", ["Sarnhad"] = "PE", ["Glaniath"] = "RI", ["Tumladen"] = "RI", ["Arnach"] = "RI", ["Bar Hurin"] = "RI", ["Poste d'observation de Faramir"] = "RI", ["Imloth Melui"] = "RI", ["Minas Tirith"] = "DM", ["Crithost"] = "DM" } },
		["0DCC3"] = { Name="Peau d'un noir pur", TaskBoards = { ["Zigilgund"] = "XXX", ["Hrimbarg"] = "PT", ["Pynti-peldot"] = "LF", ["Aughaire"] = "XXX", ["Kauppa-kohta"] = "LF", ["Gabilshathur"] = "XXX", ["Suri-kyla"] = "LF", ["Tyrn Lhuig"] = "XXX" } },
		["0DCC0"] = { Name="Peau douce", TaskBoards = { ["Castelorge"] = "SM", ["Tinnudir"] = "GA", ["Esteldin"] = "RE" } },
		["4F700"] = { Name="Peau écorchée par la pierre", TaskBoards= { ["Dom Goru"] = "EMG", ["Martelieu"] = "EMG", ["Jarnfast"] = "EMG", ["Skarhald"] = "EMG" } },
		["3048E"] = { Name="Peau en lambeaux", TaskBoards = { ["Forloi"] = "PLF" } },
		["0DCC6"] = { Name="Peau feutrée", TaskBoards = { ["Gondamon"] = "PT", ["Hobbitebourg"] = "SM" } },
		--[""] = { Name="Peau grossière", TaskBoards= { ["Aldburg"] = "EO", ["Veillefeu"] = "EO", ["Gué d'Ent"] = "EO", ["Oserley"] = "EO", ["Torrepont"] = "EO", ["Gapholt"] = "EO", ["Tertrebois"] = "EO", ["Gouffre de Helm"] = "EO", ["Fenmarche"] = "EO", ["Sousharrow"] = "EO", ["Edoras"] = "EO", ["Bourgmitan"] = "EO", ["Stoke"] = "EO", ["Grimslade"] = "EO" } },
		["0DFBE"] = { Name="Peau inquiétante", TaskBoards = { ["Vingt et unième salle"] = "GF", ["Guet de l'Orque"] = "GF", ["Anazarmekhem"] = "GF", ["Refuge des Ombres"] = "GF", ["Première salle"] = "GF" } },
		["2772A"] = { Name="Peau marbrée", TaskBoards = { ["Camp de Grimbold"] = "CT", ["Brondavant"] = "CT", ["Camp d'éclaireurs rohirrim"] = "CT", ["Haldirith"] = "CS", ["Stangarde"] = "CS", ["Cuthstan"] = "CS", ["Poste de garde de Limeclaire"] = "CS", ["Parth Célébrant"] = "CS", ["Camp d'Aculf"] = "CS", ["Etheburg"] = "CS", ["Langhold"] = "XXX", ["Harwick"] = "XXX", ["Coudeflots"] = "XXX", ["Cliving"] = "XXX", ["Elthengels"] = "XXX", ["Eaworth"] = "XXX", ["Faldham"] = "XXX", ["Garsfeld"] = "XXX", ["Rangeval"] = "XXX", ["Neigebronne"] = "XXX" } },
		--[""] = { Name="Peau moisie", TaskBoards = { ["Ost Rimmon"] = "CR", ["Monture de guerre des Hommes du Roi"] = "CR", ["Camp de l'armée"] = "AO", ["Haerondir"] = "AO" } },
		["0DCBC"] = { Name="Peau mouillée", TaskBoards = { ["Bree"] = "HB" } },
		["0DCBD"] = { Name="Peau noircie", TaskBoards = { ["Bree"] = "HB", ["Auberge abandonnée"] = "EG" } },
		["54D6D"] = { Name="Peau raffermie", TaskBoards = { ["Estolad Lan"] = "CB" } },
		["0DCBF"] = { Name="Peau rugueuse", TaskBoards = { ["Meluinen"] = "EFO", ["Othrikar"] = "PT", ["Esteldin"] = "RE", ["Auberge abandonnée"] = "EG", ["Amon Raith"] = "RE", ["Pont-à-Tréteaux"] = "HB", ["Fort d'Udûn"] = "CGO", ["Ruines de Dingarth"] = "CGO", ["Magh Ashtu"] = "CGO" } },
		--[""] = { Name="Peau tachée", TaskBoards = { ["Langhold"] = "XXX", ["Harwick"] = "XXX", ["Coudeflots"] = "XXX", ["Cliving"] = "XXX", ["Elthengels"] = "XXX", ["Eaworth"] = "XXX", ["Faldham"] = "XXX", ["Garsfeld"] = "XXX", ["Rangeval"] = "XXX", ["Neigebronne"] = "XXX" } },
		["0DFBC"] = { Name="Peau tachetée", TaskBoards = { ["Belvédère Enfoui"] = "GF", ["Longue Descente"] = "GF", ["Cellier Putride"] = "GF", ["Salle de la Croisée des Chemins"] = "GF", ["Jazargund"] = "GF" } },
		["27730"] = { Name="Peau tendue", TaskBoards = { ["Galtrev"] = "HPD", ["Lhan Tarren"] = "HPD", ["Avardin"] = "HPD", ["Barnavon"] = "HPD", ["Lhan Rhos"] = "HPD" } },
		["0DAF5"] = { Name="Phalange décrépite", TaskBoards = { ["Agamaur"] = "EG" } },
		["0DAF3"] = { Name="Phalange rongée", TaskBoards = { ["Bree"] = "HB" } },
		["0DAF6"] = { Name="Phalange striée", TaskBoards = { ["Thorenhad"] = "EFO" } },
		["0DBD0"] = { Name="Plume feutrée", TaskBoards = { ["Gondamon"] = "PT" } },
		["0DBC9"] = { Name="Plume froissée", TaskBoards = { ["Othrikar"] = "PT", ["Ost Guruth"] = "EG", ["Esteldin"] = "RE" } },
		["0DBFE"] = { Name="Queue entaillée", TaskBoards = { ["Esteldin"] = "RE" } },
		["54D36"] = { Name="Queue flagellante", TaskBoards = { ["Limlok"] = "PLF", ["Thokvist"] = "PLF" } },
		["0DC01"] = { Name="Queue propre", TaskBoards = { ["Zigilgund"] = "XXX", ["Gabilshathur"] = "XXX" } },
		--[""] = { Name="Queue épaisse", TaskBoards = { ["Camp de Grimbold"] = "CT", ["Haldirith"] = "CS", ["Stangarde"] = "CS", ["Cuthstan"] = "CS", ["Poste de garde de Limeclaire"] = "CS", ["Parth Célébrant"] = "CS", ["Camp d'Aculf"] = "CS", ["Etheburg"] = "CS" } },
		["4F6FB"] = { Name="Queue rocheuse", TaskBoards= { ["Dom Goru"] = "EMG", ["Martelieu"] = "EMG", ["Jarnfast"] = "EMG", ["Skarhald"] = "EMG" } },
		["2771C"] = { Name="Saleté boueuse", TaskBoards = { ["Galtrev"] = "HPD", ["Lhan Tarren"] = "HPD", ["Avardin"] = "HPD", ["Barnavon"] = "HPD", ["Lhan Rhos"] = "HPD" } },
		["0DAEB"] = { Name="Saleté collante", TaskBoards = { ["Tinnudir"] = "GA", ["Castelorge"] = "SM", ["Esteldin"] = "RE" } },
		["0DAF1"] = { Name="Saleté crasseuse", TaskBoards = { ["Gondamon"] = "PT", ["Hobbitebourg"] = "SM" } },
		["0DAED"] = { Name="Saleté énorme", TaskBoards = { ["Tyrn Lhuig"] = "XXX", ["Aughaire"] ="XXX" } },
		--[""] = { Name="Saleté fétide", TaskBoards = { ["Langhold"] = "XXX", ["Harwick"] = "XXX", ["Coudeflots"] = "XXX", ["Cliving"] = "XXX", ["Elthengels"] = "XXX", ["Eaworth"] = "XXX", ["Faldham"] = "XXX", ["Garsfeld"] = "XXX", ["Rangeval"] = "XXX", ["Neigebronne"] = "XXX" } },
		["0DAEE"] = { Name="Saleté impressionnante", TaskBoards = { ["Gabilshathur"] = "XXX", ["Kauppa-kohta"] = "LF" } },
		["0DEA8"] = { Name="Saleté inquiétante", TaskBoards = { ["Belvédère Enfoui"] = "GF", ["Longue Descente"] = "GF", ["Cellier Putride"] = "GF", ["Salle de la Croisée des Chemins"] = "GF", ["Jazargund"] = "GF" } },
		["0DAE9"] = { Name="Saleté luisante", TaskBoards = { ["Bree"] = "HB" } },
		["0DEAA"] = { Name="Saleté ignoble", TaskBoards = { ["Vingt et unième salle"] = "GF", ["Guet de l'Orque"] = "GF", ["Anazarmekhem"] = "GF", ["Refuge des Ombres"] = "GF", ["Première salle"] = "GF" } },
		["0DAE8"] = { Name="Saleté noircie", TaskBoards = { ["Bree"] = "HB" } },
		["0DAEF"] = { Name="Saleté monstrueuse", TaskBoards = { ["Gath Forthnir"] = "CN", ["Gwingris"] = "XXX" } },
		["4F6F4"] = { Name="Saleté parsemée de cailloux", TaskBoards = { ["Arhaim"] = "PS", ["Beorninghus"] = "PS", ["Blomgard"] = "PS", ["Hultvis"] = "PS", ["Vegbar"] = "PS" } },
		--[""] = { Name="Saleté puante", TaskBoards = { ["Camp de l'armée"] = "AO", ["Haerondir"] = "AO" } },
		["54D73"] = { Name="Saleté repoussante", TaskBoards = { ["Estolad Lan"] = "CB" } },
		["0DAEC"] = { Name="Saleté soyeuse", TaskBoards = { ["Echad Candelleth"] = "EFO", ["Thorenhad"] = "EFO" } },
		--[""] = { Name="Saleté toxique", TaskBoards= { ["Calembel"] = "DA", ["Dinadab"] = "DA", ["Dol Amroth"] = "DA", ["Morlad"] = "DA", ["Tadrent"] = "DA", ["Glaniath"] = "RI", ["Tumladen"] = "RI", ["Arnach"] = "RI", ["Bar Hurin"] = "RI", ["Poste d'observation de Faramir"] = "RI", ["Imloth Melui"] = "RI" } },
		["30494"] = { Name="Saleté visqueuse", TaskBoards = { ["Forloi"] = "PLF" } },
		--[""] = { Name="Sécrétion bouillonnante", TaskBoards = { ["Camp de l'armée"] = "AO", ["Haerondir"] = "AO" } },
		["0DBA9"] = { Name="Sécrétion bulbeuse", TaskBoards = { ["Bree"] = "HB" } },
		--[""] = { Name="Sécrétion collante", TaskBoards = { ["Camp de Grimbold"] = "CT", ["Haldirith"] = "CS", ["Stangarde"] = "CS", ["Cuthstan"] = "CS", ["Poste de garde de Limeclaire"] = "CS", ["Parth Célébrant"] = "CS", ["Camp d'Aculf"] = "CS", ["Etheburg"] = "CS" } },
		--[""] = { Name="Sécrétion épaissie", TaskBoards = { ["Minas Tirith"] = "DM", ["Crithost"] = "DM" } },
		["0DBAB"] = { Name="Sécrétion gélatineuse", TaskBoards = { ["Castelorge"] = "SM" } },
		["0DBAC"] = { Name="Sécrétion grise", TaskBoards = { ["Echad Candelleth"] = "EFO" } },
		["0DBAA"] = { Name="Sécrétion imparfaite", TaskBoards = { ["Meluinen"] = "EFO", ["Esteldin"] = "RE", ["Ost Guruth"] = "EG" } },
		["0DBAF"] = { Name="Sécrétion monstrueuse", TaskBoards = { ["Gwingris"] = "XXX" } },
		["0DBB1"] = { Name="Sécrétion spongieuse", TaskBoards = { ["Gondamon"] = "PT", ["Hobbitebourg"] = "SM" } },
		--[""] = { Name="Tas de poudre étincelante", TaskBoards = { ["Camp de Grimbold"] = "CT", ["Haldirith"] = "CS", ["Stangarde"] = "CS", ["Cuthstan"] = "CS", ["Poste de garde de Limeclaire"] = "CS", ["Parth Célébrant"] = "CS", ["Camp d'Aculf"] = "CS", ["Etheburg"] = "CS", ["Calembel"] = "DA", ["Dinadab"] = "DA", ["Dol Amroth"] = "DA", ["Morlad"] = "DA", ["Tadrent"] = "DA" } },
		["0DC5A"] = { Name="Tas de poussière brillante", TaskBoards = { ["Kauppa-kohta"] = "LF" } },
		["0DC56"] = { Name="Tas de poussière imprécise", TaskBoards = { ["Amon Raith"] = "RE" } },
		["0DC57"] = { Name="Tas de poussière terne", TaskBoards = { ["Tinnudir"] = "GA" } },
	},

	junk = {
		["0DB67"] = { Name="Aile impressionnante" },
		["4F6F6"] = { Name="Aile perforée" },
		["0F799"] = { Name="Arbalète cassée" },
		["4F703"] = { Name="Bec ébréché" },
		["4F6F8"] = { Name="Branche calcifiée" },
		["0DC2E"] = { Name="Branche torse" },
		["0DF74"] = { Name="Carapace barbelée" },
		["3047A"] = { Name="Carapace brillante" },
		["0DF78"] = { Name="Carapace effilée" },
		["54D59"] = { Name="Carapace épaisse" },
		["0DF76"] = { Name="Carapace irrégulière" },
		["4B96E"] = { Name="Duramen calciné" },
		["54D24"] = { Name="Duramen qui bat" },
		["4F6FF"] = { Name="Écaille fragile" },
		["30485"] = { Name="Ecaille irrégulière" },
		["0DB29"] = { Name="Ecaille monstrueuse"},
		["0DECA"] = { Name="Ecaille somptueuse"},
		["0DB9B"] = { Name="Essence ardente"},
		["30486"] = { Name="Essence fluide" },
		["4B975"] = { Name="Essence inquiétante" },
		["0DB9A"] = { Name="Essence luisante"},
		["0DB98"] = { Name="Essence rutilante"},
		["0DB99"] = { Name="Essence scintillante"},
		["54D66"] = { Name="Essence ténébreuse" },
		["4B971"] = { Name="Fourreau d'épée orque" },
		["0F79B"] = { Name="Gourdin métallique cassé"},
		["0F79A"] = { Name="Grand marteau cassé" },
		["0DEA6"] = { Name="Griffe effilée" },
		["30493"] = { Name="Griffe aiguisée" },
		["4F869"] = { Name="Hache brisée" },
		["0F798"] = { Name="Hache cassée" },
		["0DCAF"] = { Name="Membrane monstrueuse"},
		["0DFC0"] = { Name="Peau ignoble"},
		["0DAF7"] = { Name="Phalange millénaire"},
		["3A750"] = { Name="Phalange tordue"},
		["4F6FD"] = { Name="Plume usée" },
		["0DBC7"] = { Name="Plume noircie" },
		["4F6F7"] = { Name="Poussière grise" },
		["3047E"] = { Name="Poussière noire" },
		["54D51"] = { Name="Poussière ténébreuse" },
		["30487"] = { Name="Queue brûlée" },
		["0DC02"] = { Name="Queue élégante" },
		["0DBFF"] = { Name="Queue grise" },
		["0DF4C"] = { Name="Queue lisse" },
		["0DF4E"] = { Name="Queue somptueuse" },
		["54D53"] = { Name="Relique d'os" },
		["0DEAC"] = { Name="Saleté abjecte" },
		["30480"] = { Name="Sécrétion conservée" },
		["0DF16"] = { Name="Sécrétion ignoble" },
		["0DF14"] = { Name="Sécrétion inquiétante" },
		["54D55"] = { Name="Sécrétion noire lustrée" },
		["0DC59"] = { Name="Tas de poussière chatoyante" },
		["4B970"] = { Name="Tas de poussière étouffante" },
		["0DC58"] = { Name="Tas de poussière indistincte" },
		["0DC5B"] = { Name="Tas de poussière lumineuse" },
	},
}